
package wsdl.local;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LocalPaymentAuthorizorService", targetNamespace = "http://ticketincoesb.com/", wsdlLocation = "file:/home/jhagopian/git/f/TicketInco/src/main/resources/META-INF/wsdl/localValidationService.wsdl")
public class LocalPaymentAuthorizorService
    extends Service
{

    private final static URL LOCALPAYMENTAUTHORIZORSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCALPAYMENTAUTHORIZORSERVICE_EXCEPTION;
    private final static QName LOCALPAYMENTAUTHORIZORSERVICE_QNAME = new QName("http://ticketincoesb.com/", "LocalPaymentAuthorizorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jhagopian/git/f/TicketInco/src/main/resources/META-INF/wsdl/localValidationService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCALPAYMENTAUTHORIZORSERVICE_WSDL_LOCATION = url;
        LOCALPAYMENTAUTHORIZORSERVICE_EXCEPTION = e;
    }

    public LocalPaymentAuthorizorService() {
        super(__getWsdlLocation(), LOCALPAYMENTAUTHORIZORSERVICE_QNAME);
    }

    public LocalPaymentAuthorizorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCALPAYMENTAUTHORIZORSERVICE_QNAME, features);
    }

    public LocalPaymentAuthorizorService(URL wsdlLocation) {
        super(wsdlLocation, LOCALPAYMENTAUTHORIZORSERVICE_QNAME);
    }

    public LocalPaymentAuthorizorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCALPAYMENTAUTHORIZORSERVICE_QNAME, features);
    }

    public LocalPaymentAuthorizorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocalPaymentAuthorizorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocalPaymentAuthorizor
     */
    @WebEndpoint(name = "LocalPaymentAuthorizorPort")
    public LocalPaymentAuthorizor getLocalPaymentAuthorizorPort() {
        return super.getPort(new QName("http://ticketincoesb.com/", "LocalPaymentAuthorizorPort"), LocalPaymentAuthorizor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalPaymentAuthorizor
     */
    @WebEndpoint(name = "LocalPaymentAuthorizorPort")
    public LocalPaymentAuthorizor getLocalPaymentAuthorizorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ticketincoesb.com/", "LocalPaymentAuthorizorPort"), LocalPaymentAuthorizor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCALPAYMENTAUTHORIZORSERVICE_EXCEPTION!= null) {
            throw LOCALPAYMENTAUTHORIZORSERVICE_EXCEPTION;
        }
        return LOCALPAYMENTAUTHORIZORSERVICE_WSDL_LOCATION;
    }

}
