
package wsdlgenerated;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocalPaymentAuthorizor", targetNamespace = "http://ticketincoesb.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocalPaymentAuthorizor {


    /**
     * 
     * @param request
     */
    @WebMethod(action = "voidPayment")
    @RequestWrapper(localName = "voidPayment", targetNamespace = "http://ticketincoesb.com/", className = "wsdlgenerated.VoidPayment")
    @ResponseWrapper(localName = "voidPaymentResponse", targetNamespace = "http://ticketincoesb.com/", className = "wsdlgenerated.VoidPaymentResponse")
    public void voidPayment(
        @WebParam(name = "request", targetNamespace = "")
        PagosYaVoidRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns wsdlgenerated.LocalPaymentResponse
     */
    @WebMethod(action = "authorizePayment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorizePayment", targetNamespace = "http://ticketincoesb.com/", className = "wsdlgenerated.AuthorizePayment")
    @ResponseWrapper(localName = "authorizePaymentResponse", targetNamespace = "http://ticketincoesb.com/", className = "wsdlgenerated.AuthorizePaymentResponse")
    public LocalPaymentResponse authorizePayment(
        @WebParam(name = "request", targetNamespace = "")
        LocalPaymentRequest request);

}
