
package wsdl.pagoya;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PagosYaPaymentAuthorizor", targetNamespace = "http://ticketincoesb.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PagosYaPaymentAuthorizor {


    /**
     * 
     * @param request
     * @return
     *     returns wsdl.pagoya.PagosYaVoidResponse
     */
    @WebMethod(action = "voidPayment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "voidPayment", targetNamespace = "http://ticketincoesb.com/", className = "wsdl.pagoya.VoidPayment")
    @ResponseWrapper(localName = "voidPaymentResponse", targetNamespace = "http://ticketincoesb.com/", className = "wsdl.pagoya.VoidPaymentResponse")
    public PagosYaVoidResponse voidPayment(
        @WebParam(name = "request", targetNamespace = "")
        PagosYaVoidRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns wsdl.pagoya.PagosYaPaymentResponse
     */
    @WebMethod(action = "authorizePayment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorizePayment", targetNamespace = "http://ticketincoesb.com/", className = "wsdl.pagoya.AuthorizePayment")
    @ResponseWrapper(localName = "authorizePaymentResponse", targetNamespace = "http://ticketincoesb.com/", className = "wsdl.pagoya.AuthorizePaymentResponse")
    public PagosYaPaymentResponse authorizePayment(
        @WebParam(name = "request", targetNamespace = "")
        PagosYaPaymentRequest request);

}
